### ISSUE TITLE
[bug] 从首页 Decentraland-->Analytics 点击小黄条，跳转后未定位到Decentraland

### ISSUE THREAD

**Issue by k1ic** [themetacat/www.metacat.world#2]
![image](https://user-images.githubusercontent.com/5465932/158141894-2a976553-17d5-488e-be15-1d590b4b51d4.png)
![image](https://user-images.githubusercontent.com/5465932/158142013-a45b0730-e9da-4b39-9067-905f47788397.png)

**Comment by ZhangYuBoMetacat** [comment]
已解决
